"""Subprocess-based Python sandbox.

This sandbox is intentionally NOT Docker-based. It runs code generated by our
own LLM (the Solver), which is a relatively low-risk attack surface. The Step 4
Verifier — which executes UNTRUSTED student code — uses DockerCodeRunner.
See docs/specs/step-02-3-sandbox.md.

The shared static wrapper script and the test orchestration loop live in
app.sandbox.base_runner.TestRunner. This module only owns the subprocess +
rlimit isolation primitive.
"""

from __future__ import annotations

import asyncio
import logging
import subprocess
import sys
import tempfile
from functools import lru_cache

from app.core.config import get_settings
from app.sandbox.base_runner import TestRunner

logger = logging.getLogger("app.sandbox")


def _make_preexec_fn(memory_mb: int, timeout_seconds: int):
    """Build a preexec_fn that applies POSIX rlimits. Returns None on Windows.

    macOS does not honor RLIMIT_AS (kernel reports RLIM_INFINITY but rejects any
    attempt to lower it), so we skip the address-space limit on Darwin and rely
    on RLIMIT_CPU + the wall-clock timeout for that platform. Linux enforces
    both. Windows is logged as unsupported in run().
    """
    if sys.platform == "win32":
        return None

    import resource  # POSIX-only

    apply_as = sys.platform != "darwin"
    mem_bytes = memory_mb * 1024 * 1024
    cpu_seconds = timeout_seconds + 1

    def _apply() -> None:
        if apply_as:
            resource.setrlimit(resource.RLIMIT_AS, (mem_bytes, mem_bytes))
        resource.setrlimit(resource.RLIMIT_CPU, (cpu_seconds, cpu_seconds))

    return _apply


class PythonSubprocessRunner(TestRunner):
    """Runs the static test wrapper in an isolated local subprocess with rlimits.

    Async via asyncio.to_thread so FastAPI's event loop is never blocked by the
    blocking subprocess.run call. Test orchestration and result parsing live in
    the TestRunner base class.
    """

    def __init__(self, python_path: str | None = None) -> None:
        self._python_path = python_path or sys.executable

    async def _execute_code(
        self,
        code: str,
        payload: bytes,
        timeout_seconds: int,
        memory_mb: int,
    ) -> tuple[bytes, bytes, int, bool]:
        return await asyncio.to_thread(
            self._execute_code_sync, code, payload, timeout_seconds, memory_mb
        )

    def _execute_code_sync(
        self,
        code: str,
        payload: bytes,
        timeout_seconds: int,
        memory_mb: int,
    ) -> tuple[bytes, bytes, int, bool]:
        if sys.platform == "win32":
            logger.warning("sandbox.rlimit_skipped platform=win32")

        with tempfile.TemporaryDirectory(prefix="studyverify-sbx-") as tempdir:
            try:
                proc = subprocess.run(
                    [self._python_path, "-c", code],
                    input=payload,
                    capture_output=True,
                    timeout=timeout_seconds,
                    cwd=tempdir,
                    preexec_fn=_make_preexec_fn(memory_mb, timeout_seconds),
                    check=False,
                )
            except subprocess.TimeoutExpired:
                return b"", b"", -1, True

        return proc.stdout or b"", proc.stderr or b"", proc.returncode, False


@lru_cache
def get_sandbox_runner() -> PythonSubprocessRunner:
    settings = get_settings()
    python_path = settings.SANDBOX_PYTHON_PATH or sys.executable
    return PythonSubprocessRunner(python_path=python_path)
