"""Subprocess-based Python sandbox.

This sandbox is intentionally NOT Docker-based. It runs code generated by our
own LLM (the Solver), which is a relatively low-risk attack surface. The Step 4
Verifier — which executes UNTRUSTED student code — will use a Docker-backed
sandbox instead. See docs/specs/step-02-3-sandbox.md.

The wrapper script below is a STATIC constant. User code, the entry function
name, and test cases flow through stdin as a single JSON payload. We never
template user code into the wrapper source.
"""

from __future__ import annotations

import asyncio
import json
import logging
import subprocess
import sys
import tempfile
import time
from functools import lru_cache

from app.core.config import get_settings
from app.sandbox.schemas import SandboxRunRequest, SandboxRunResult, TestExecutionResult

logger = logging.getLogger("app.sandbox")

_STDERR_TRUNC = 500
_STDOUT_TRUNC = 500
_FATAL_EXIT_CODE = 2

WRAPPER_SCRIPT = r'''
import ast
import json
import sys
import time

def _main():
    try:
        payload = json.loads(sys.stdin.read())
        user_code = payload["code"]
        entry_function = payload["entry_function"]
        test_cases = payload["test_cases"]
    except Exception as e:
        print(f"FATAL: bad payload: {type(e).__name__}: {e}", file=sys.stderr)
        sys.exit(2)

    namespace = {}
    try:
        exec(user_code, namespace)
    except Exception as e:
        print(f"FATAL: user code failed to load: {type(e).__name__}: {e}", file=sys.stderr)
        sys.exit(2)

    fn = namespace.get(entry_function)
    if not callable(fn):
        print(f"FATAL: function {entry_function} not defined or not callable", file=sys.stderr)
        sys.exit(2)

    results = []
    for i, tc in enumerate(test_cases):
        start = time.perf_counter()
        try:
            args = ast.literal_eval(tc["input"])
            actual = fn(*args) if isinstance(args, tuple) else fn(args)
            actual_str = repr(actual)
            passed = actual_str == tc["expected"] or str(actual) == tc["expected"]
            results.append({
                "test_index": i,
                "input": tc["input"],
                "expected": tc["expected"],
                "actual": actual_str,
                "passed": passed,
                "error": None,
                "duration_ms": int((time.perf_counter() - start) * 1000),
            })
        except Exception as e:
            results.append({
                "test_index": i,
                "input": tc["input"],
                "expected": tc["expected"],
                "actual": None,
                "passed": False,
                "error": f"{type(e).__name__}: {e}",
                "duration_ms": int((time.perf_counter() - start) * 1000),
            })

    print(json.dumps(results))

_main()
'''


def _make_preexec_fn(memory_mb: int, timeout_seconds: int):
    """Build a preexec_fn that applies POSIX rlimits. Returns None on Windows.

    macOS does not honor RLIMIT_AS (kernel reports RLIM_INFINITY but rejects any
    attempt to lower it), so we skip the address-space limit on Darwin and rely
    on RLIMIT_CPU + the wall-clock timeout for that platform. Linux enforces
    both. Windows is logged as unsupported in run().
    """
    if sys.platform == "win32":
        return None

    import resource  # POSIX-only

    apply_as = sys.platform != "darwin"
    mem_bytes = memory_mb * 1024 * 1024
    cpu_seconds = timeout_seconds + 1

    def _apply() -> None:
        if apply_as:
            resource.setrlimit(resource.RLIMIT_AS, (mem_bytes, mem_bytes))
        resource.setrlimit(resource.RLIMIT_CPU, (cpu_seconds, cpu_seconds))

    return _apply


class PythonSubprocessRunner:
    """Runs user-generated Python code in an isolated subprocess.

    The runner is async: it offloads the blocking subprocess.run call onto a
    thread via asyncio.to_thread so FastAPI's event loop is never blocked.
    """

    def __init__(self, python_path: str | None = None) -> None:
        self._python_path = python_path or sys.executable

    async def run(self, request: SandboxRunRequest) -> SandboxRunResult:
        return await asyncio.to_thread(self._run_sync, request)

    def _run_sync(self, request: SandboxRunRequest) -> SandboxRunResult:
        if sys.platform == "win32":
            logger.warning("sandbox.rlimit_skipped platform=win32")

        payload = json.dumps(
            {
                "code": request.code,
                "entry_function": request.entry_function,
                "test_cases": request.test_cases,
            }
        )
        wall_start = time.perf_counter()
        with tempfile.TemporaryDirectory(prefix="studyverify-sbx-") as tempdir:
            try:
                proc = subprocess.run(
                    [self._python_path, "-c", WRAPPER_SCRIPT],
                    input=payload,
                    capture_output=True,
                    text=True,
                    timeout=request.timeout_seconds,
                    cwd=tempdir,
                    preexec_fn=_make_preexec_fn(request.memory_mb, request.timeout_seconds),
                    check=False,
                )
            except subprocess.TimeoutExpired:
                wall_ms = int((time.perf_counter() - wall_start) * 1000)
                logger.info(
                    "sandbox.run entry_function=%s n_tests=%d status=timeout wall_ms=%d",
                    request.entry_function,
                    len(request.test_cases),
                    wall_ms,
                )
                return SandboxRunResult(
                    status="timeout",
                    test_results=[],
                    pass_count=0,
                    fail_count=0,
                    error=f"subprocess exceeded {request.timeout_seconds}s timeout",
                )

        wall_ms = int((time.perf_counter() - wall_start) * 1000)
        result = self._parse_proc_result(proc, request)
        logger.info(
            "sandbox.run entry_function=%s n_tests=%d pass=%d fail=%d status=%s "
            "wall_ms=%d returncode=%d",
            request.entry_function,
            len(request.test_cases),
            result.pass_count,
            result.fail_count,
            result.status,
            wall_ms,
            proc.returncode,
        )
        return result

    @staticmethod
    def _parse_proc_result(
        proc: subprocess.CompletedProcess, request: SandboxRunRequest
    ) -> SandboxRunResult:
        if proc.returncode == _FATAL_EXIT_CODE:
            return SandboxRunResult(
                status="error",
                test_results=[],
                pass_count=0,
                fail_count=0,
                error=(proc.stderr or "")[:_STDERR_TRUNC].strip() or "wrapper FATAL",
            )

        if proc.returncode != 0:
            stderr_snippet = (proc.stderr or "")[:_STDERR_TRUNC].strip()
            return SandboxRunResult(
                status="error",
                test_results=[],
                pass_count=0,
                fail_count=0,
                error=(
                    f"subprocess exited with code {proc.returncode}: "
                    f"{stderr_snippet or '(no stderr)'}"
                ),
            )

        try:
            raw_results = json.loads(proc.stdout)
        except json.JSONDecodeError:
            stdout_snippet = (proc.stdout or "")[:_STDOUT_TRUNC]
            return SandboxRunResult(
                status="error",
                test_results=[],
                pass_count=0,
                fail_count=0,
                error=f"failed to parse wrapper stdout as JSON: {stdout_snippet!r}",
            )

        test_results = [TestExecutionResult.model_validate(r) for r in raw_results]
        pass_count = sum(1 for r in test_results if r.passed)
        fail_count = len(test_results) - pass_count
        status = "all_passed" if fail_count == 0 and test_results else "some_failed"
        return SandboxRunResult(
            status=status,
            test_results=test_results,
            pass_count=pass_count,
            fail_count=fail_count,
            error=None,
        )


@lru_cache
def get_sandbox_runner() -> PythonSubprocessRunner:
    settings = get_settings()
    python_path = settings.SANDBOX_PYTHON_PATH or sys.executable
    return PythonSubprocessRunner(python_path=python_path)
