"""add hint_sessions table

Revision ID: 02dbc0b244cb
Revises: f3541344b480
Create Date: 2026-05-02 02:12:54.585876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02dbc0b244cb'
down_revision: Union[str, Sequence[str], None] = 'f3541344b480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hint_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verifier_session_id', sa.Uuid(), nullable=False),
    sa.Column('hint_index', sa.Integer(), nullable=False),
    sa.Column('hint_text', sa.Text(), nullable=False),
    sa.Column('prior_hints_count', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verifier_session_id'], ['verifier_sessions.id'], name=op.f('fk_hint_sessions_verifier_session_id_verifier_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hint_sessions')),
    sa.UniqueConstraint('verifier_session_id', 'hint_index', name='uq_hint_sessions_verifier_index')
    )
    op.create_index(op.f('ix_hint_sessions_created_at'), 'hint_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_hint_sessions_verifier_session_id'), 'hint_sessions', ['verifier_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hint_sessions_verifier_session_id'), table_name='hint_sessions')
    op.drop_index(op.f('ix_hint_sessions_created_at'), table_name='hint_sessions')
    op.drop_table('hint_sessions')
    # ### end Alembic commands ###
