"""create solver_sessions table

Revision ID: 0b3015bfb3f1
Revises: 
Create Date: 2026-04-28 01:17:25.086081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b3015bfb3f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solver_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.String(length=64), nullable=False),
    sa.Column('problem_text', sa.Text(), nullable=False),
    sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('plan_steps', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('test_results', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solver_sessions'))
    )
    op.create_index(op.f('ix_solver_sessions_created_at'), 'solver_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_solver_sessions_problem_id'), 'solver_sessions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_solver_sessions_verified'), 'solver_sessions', ['verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solver_sessions_verified'), table_name='solver_sessions')
    op.drop_index(op.f('ix_solver_sessions_problem_id'), table_name='solver_sessions')
    op.drop_index(op.f('ix_solver_sessions_created_at'), table_name='solver_sessions')
    op.drop_table('solver_sessions')
    # ### end Alembic commands ###
